version: '2'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx:stable-alpine
    volumes:
      - /root/lamp-xoops/xoops:/var/www
      - /root/lamp-xoops/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      app_net:
        ipv4_address: 172.18.0.2
  php-fpm:
    container_name: php-fpm
    restart: always
    image: lyshie/php-fpm-xoops
    volumes:
      - /root/lamp-xoops/xoops:/var/www
    ports:
      - "9000:9000"
    networks:
      app_net:
        ipv4_address: 172.18.0.3
  mysql:
    container_name: mysql
    restart: always
    image: mariadb:5.5
    volumes:
      - /root/lamp-xoops/xoops/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      app_net:
        ipv4_address: 172.18.0.4
    environment:
       MYSQL_ROOT_PASSWORD: Admin2015

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24
        gateway: 172.18.0.1

